### ISSUE TITLE
Hi, unable to access GST/Foundation/Dashboard

### ISSUE THREAD

**Issue by akatbo** [dolfdijkstra/gst-foundation#36]
I am getting the following errors, how do I fix this??

[2014-11-29 13:02:22,289 SAST] [ERROR] [.kernel.Default (self-tuning)'] [fatwire.logging.cs.request] Exception including resource /jsp/cs_deployed/GST/Foundation/Dashboard.jsp
javax.servlet.ServletException: weblogic.servlet.jsp.CompilationException: Failed to compile JSP /jsp/cs_deployed/GST/Foundation/Dashboard.jsp
Dashboard.jsp:22:5: No tag library could be found with this URI. Possible causes could be that the URI is incorrect, or that there were errors during parsing of the .tld file.
<%@ taglib prefix="gsf" uri="http://gst.fatwire.com/foundation/tags/gsf"%>
    ^----^
Dashboard.jsp:22:5: No tag library could be found with this URI. Possible causes could be that the URI is incorrect, or that there were errors during parsing of the .tld file.
<%@ taglib prefix="gsf" uri="http://gst.fatwire.com/foundation/tags/gsf"%>
    ^----^
Dashboard.jsp:23:5: No tag library could be found with this URI. Possible causes could be that the URI is incorrect, or that there were errors during parsing of the .tld file.
<%@ taglib prefix="gsf-install"
    ^----^
Dashboard.jsp:23:5: No tag library could be found with this URI. Possible causes could be that the URI is incorrect, or that there were errors during parsing of the .tld file.
<%@ taglib prefix="gsf-install"
    ^----^

```
    at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:261)
    at weblogic.servlet.internal.ServletStubImpl.onAddToMapException(ServletStubImpl.java:417)
    at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:327)
    at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:185)
    at weblogic.servlet.internal.RequestDispatcherImpl.invokeServlet(RequestDispatcherImpl.java:526)
    at weblogic.servlet.internal.RequestDispatcherImpl.include(RequestDispatcherImpl.java:447)
    at COM.FutureTense.Servlet.ServletRequest.include(ServletRequest.java:1411)
    at COM.FutureTense.Servlet.FRequestObj.include(FRequestObj.java:1429)
    at COM.FutureTense.Servlet.JSPServices.runJSP(JSPServices.java:111)
    at COM.FutureTense.Platform.FileSystem.FILESYSTEMJSPManager.runJSP(FILESYSTEMJSPManager.java:463)
    at COM.FutureTense.Servlet.JSPServices.runJSPObject(JSPServices.java:50)
    at COM.FutureTense.Platform.FileSystem.FILESYSTEMJSPManager$JSPDataFile.run(FILESYSTEMJSPManager.java:190)
    at COM.FutureTense.Common.ContentServer.jspExecute(ContentServer.java:2936)
    at COM.FutureTense.Common.ContentServer.evalTemplate(ContentServer.java:2530)
    at COM.FutureTense.Common.ContentServer.generatePage(ContentServer.java:1549)
    at COM.FutureTense.Common.ContentServer.evalPage(ContentServer.java:1248)
    at COM.FutureTense.Common.ContentServer.execute(ContentServer.java:454)
    at COM.FutureTense.Servlet.FTServlet.execute(FTServlet.java:129)
    at COM.FutureTense.Servlet.FTServlet.doGet(FTServlet.java:54)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:821)
    at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
    at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
    at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:301)
    at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:27)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:57)
    at com.fatwire.auth.RequestAuthenticationFilter.doFilter(RequestAuthenticationFilter.java:192)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:57)
    at com.fatwire.wem.sso.cas.filter.CASFilter.doFilter(CASFilter.java:252)
    at com.fatwire.wem.sso.SSOFilter.doFilter(SSOFilter.java:51)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:57)
    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3730)
    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3696)
    at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
    at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
    at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2273)
    at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2179)
    at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1490)
    at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)
    at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)
```

Caused by: weblogic.servlet.jsp.CompilationException: Failed to compile JSP /jsp/cs_deployed/GST/Foundation/Dashboard.jsp
Dashboard.jsp:22:5: No tag library could be found with this URI. Possible causes could be that the URI is incorrect, or that there were errors during parsing of the .tld file.
<%@ taglib prefix="gsf" uri="http://gst.fatwire.com/foundation/tags/gsf"%>
    ^----^
Dashboard.jsp:22:5: No tag library could be found with this URI. Possible causes could be that the URI is incorrect, or that there were errors during parsing of the .tld file.
<%@ taglib prefix="gsf" uri="http://gst.fatwire.com/foundation/tags/gsf"%>
    ^----^
Dashboard.jsp:23:5: No tag library could be found with this URI. Possible causes could be that the URI is incorrect, or that there were errors during parsing of the .tld file.
<%@ taglib prefix="gsf-install"
    ^----^
Dashboard.jsp:23:5: No tag library could be found with this URI. Possible causes could be that the URI is incorrect, or that there were errors during parsing of the .tld file.
<%@ taglib prefix="gsf-install"

**Comment by sivaranjanikannan** [comment]
Hi, 
I am also getting the same error as above. Can anyone help me to reolve this issue.

Thanks,
Ranjani

**Comment by tfield** [comment]
HI. Where have you placed the jar exactly? What is the full path to the jar?

**Comment by sivaranjanikannan** [comment]
I have placed the jar into <CS-deployed-path>/CS/WEB-INF/lib

**Comment by sivaranjanikannan** [comment]
To install GSF, am using the url 
<ip:port>/cs/ContentServer?pagename=GST/Foundation/Installer

then getting error in UI like

![image](https://cloud.githubusercontent.com/assets/22391086/18858780/304a62c4-84a1-11e6-9f2d-1be0fbcec798.png)

Sites log error is below.

After clicking on the "Install/reinstall GSF components" link showing content server error and in sites log

[2016-09-27 10:54:28,686 MYT] [ERROR] [.kernel.Default (self-tuning)'] [fatwire.logging.cs.request] Exception including resource /jsp/cs_deployed/GST/Foundation/Dashboard.jsp
java.lang.NullPointerException
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3357)
	at java.util.Arrays.asList(Arrays.java:3343)
	at com.fatwire.gst.foundation.taglib.install.Install.doTag(Install.java:45)
	at jsp_servlet._jsp._cs_deployed._gst._foundation.__dashboard._jspService(__dashboard.java:244)
	at weblogic.servlet.jsp.JspBase.service(JspBase.java:35)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:300)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:184)
	at weblogic.servlet.internal.RequestDispatcherImpl.invokeServlet(RequestDispatcherImpl.java:523)
	at weblogic.servlet.internal.RequestDispatcherImpl.include(RequestDispatcherImpl.java:444)
	at COM.FutureTense.Servlet.ServletRequest.include(ServletRequest.java:1411)
	at COM.FutureTense.Servlet.FRequestObj.include(FRequestObj.java:1429)
	at COM.FutureTense.Servlet.JSPServices.runJSP(JSPServices.java:111)
	at COM.FutureTense.Platform.FileSystem.FILESYSTEMJSPManager.runJSP(FILESYSTEMJSPManager.java:463)
	at COM.FutureTense.Servlet.JSPServices.runJSPObject(JSPServices.java:50)
	at COM.FutureTense.Platform.FileSystem.FILESYSTEMJSPManager$JSPDataFile.run(FILESYSTEMJSPManager.java:190)
	at COM.FutureTense.Common.ContentServer.jspExecute(ContentServer.java:2936)
	at COM.FutureTense.Common.ContentServer.evalTemplate(ContentServer.java:2530)
	at COM.FutureTense.Common.ContentServer.generatePage(ContentServer.java:1549)
	at COM.FutureTense.Common.ContentServer.evalPage(ContentServer.java:1248)
	at COM.FutureTense.Common.ContentServer.execute(ContentServer.java:454)
	at COM.FutureTense.Servlet.FTServlet.execute(FTServlet.java:129)
	at COM.FutureTense.Servlet.FTServlet.doGet(FTServlet.java:54)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:821)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:300)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:27)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:57)
	at com.fatwire.auth.RequestAuthenticationFilter.doFilter(RequestAuthenticationFilter.java:192)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:57)
	at com.fatwire.wem.sso.cas.filter.CASFilter.doFilter(CASFilter.java:252)
	at com.fatwire.wem.sso.SSOFilter.doFilter(SSOFilter.java:51)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:57)
	at com.fatwire.cs.ui.framework.UIFilter.doFilter(UIFilter.java:109)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:57)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:57)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3715)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3681)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2277)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2183)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1454)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:209)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:178)
[2016-09-27 10:54:28,686 MYT] [ERROR] [.kernel.Default (self-tuning)'] [fatwire.logging.cs.jsp] Failure executing JSPGST/Foundation/Dashboard Exception calling include:  page:/jsp/cs_deployed/GST/Foundation/Dashboard.jsp
java.lang.NullPointerException tossed:null
[2016-09-27 10:54:28,686 MYT] [WARN ] [.kernel.Default (self-tuning)'] [logging.cs.cache.page] Explicitly disabling page cache (recursive=true) for pagename=GST/Foundation/Dashboard&ft_ss=false
[2016-09-27 10:54:28,687 MYT] [ERROR] [.kernel.Default (self-tuning)'] [fatwire.logging.cs.request] COM.FutureTense.Common.ContentServerException: Unable to evaluate element GST/Foundation/Dashboard Error code:UNABLE TO EVAL ELEMENT



Please help me to solve the issue. I am new to the GSF. I have followed hte steps mentioned in 
http://gst-foundation.org/gsf-11.6.0/site/InstallGuide.html.
